 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/theaters", type: :request do
  
  # Theater. As you add validations to Theater, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Theater.create! valid_attributes
      get theaters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      theater = Theater.create! valid_attributes
      get theater_url(theater)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_theater_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      theater = Theater.create! valid_attributes
      get edit_theater_url(theater)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Theater" do
        expect {
          post theaters_url, params: { theater: valid_attributes }
        }.to change(Theater, :count).by(1)
      end

      it "redirects to the created theater" do
        post theaters_url, params: { theater: valid_attributes }
        expect(response).to redirect_to(theater_url(Theater.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Theater" do
        expect {
          post theaters_url, params: { theater: invalid_attributes }
        }.to change(Theater, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post theaters_url, params: { theater: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested theater" do
        theater = Theater.create! valid_attributes
        patch theater_url(theater), params: { theater: new_attributes }
        theater.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the theater" do
        theater = Theater.create! valid_attributes
        patch theater_url(theater), params: { theater: new_attributes }
        theater.reload
        expect(response).to redirect_to(theater_url(theater))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        theater = Theater.create! valid_attributes
        patch theater_url(theater), params: { theater: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested theater" do
      theater = Theater.create! valid_attributes
      expect {
        delete theater_url(theater)
      }.to change(Theater, :count).by(-1)
    end

    it "redirects to the theaters list" do
      theater = Theater.create! valid_attributes
      delete theater_url(theater)
      expect(response).to redirect_to(theaters_url)
    end
  end
end
